import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8').replace(/\r\n/g, '\n');
const write = (name, value) => fs.writeFileSync(path.join(root, name), value);
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const today = read('mobile-web/01-today.html');
const start = today.indexOf('<div class="device">');
const end = today.indexOf('<p class="caption">', start);
if (start < 0 || end < 0) throw Error('Cannot extract the approved Today specimen');
let specimen = today.slice(start, end).trim();
// Documentation-only viewport and a real field to exercise focus while tucked.
specimen = specimen.replace('<div class="device">', '<div class="ds-motion-viewport" tabindex="0" aria-label="Today motion specimen, scroll to test the composer">');
specimen = specimen.replace('<div class="field placeholder">Add to today</div>', '<input class="field" aria-label="Add to today, motion specimen only" placeholder="Add to today">');
specimen = specimen.replace(/href="[^"]*"/g, 'href="#motion"');
specimen = specimen.replace(/id="[^"]*"/g, '');
const sourcePath = 'design system/index.source.html';
const guide = read(sourcePath);
const specimenPattern = /<!-- MOTION SPECIMEN START -->[\s\S]*?<!-- MOTION SPECIMEN END -->/;
if (!specimenPattern.test(guide)) throw Error('Missing motion specimen seam');
write(sourcePath, guide.replace(specimenPattern, () => `<!-- MOTION SPECIMEN START -->\n${specimen}\n<!-- MOTION SPECIMEN END -->`));


const rows = [];
for (const file of fs.readdirSync(path.join(root, 'mobile-web')).filter(name => /^\d{2}-/.test(name) && !name.startsWith('00-'))) {
  const html = read(`mobile-web/${file}`);
  const label = file.replace(/^\d+-/, '').replace('.html', '').replaceAll('-', ' ');
  const description = html.match(/<b>What moves:<\/b>\s*([\s\S]*?)<br>/)?.[1]?.trim() || 'Later handover pages: C3 typing on introductory product copy and existing control feedback. Errors, fields and progress remain immediate.';
  rows.push(`<div class="srow"><div class="tcol">${file.slice(0,2)}</div><div class="ccol"><h2 class="shead">${escape(label)}</h2><p class="lede">${description}</p><p>${['mobile-web','tablet-web','desktop-web'].map(platform => `<a class="cite" href="${platform}/${file}">${platform.replace('-web','')}</a>`).join(' / ')}</p></div></div>`);
}
write('motion-index.html', `<!doctype html>
<!-- GENERATED by scripts/build-motion.mjs from current numbered screens. -->
<html lang="en" data-motion-review="play"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Journal / C3 motion handover</title><link rel="stylesheet" href="lock.css"></head><body>
<p class="caption"><b>C3 glide / motion handover</b><br>These links open the full current screens, including the account extension. Reload a screen to replay its arrival. Motion preview is enabled even when Windows animation effects are disabled, as requested. Device settings are unchanged.</p>
<div class="device"><div class="app"><div class="page"><h1 class="wordmark">Motion</h1><div class="sheet">
<div class="srow"><div class="ccol"><h2 class="shead">Start here</h2><p><a class="cite" href="design%20system/index.html#motion">Interactive motion design system</a></p><p><a class="cite" href="MOTION-HANDOVER.md">Implementation contract and acceptance checks</a></p><p><a class="cite" href="journal-prototype.html">Current mobile walkthrough with motion</a></p></div></div>
<div class="srow"><div class="ccol"><h2 class="shead">Complete walkthroughs</h2><p><a class="cite" href="journal-prototype.html">Mobile</a> / <a class="cite" href="journal-prototype-tablet.html">Tablet</a> / <a class="cite" href="journal-prototype-desktop.html">Desktop</a></p><p class="lede">Static hash navigation replays arrival on Back and some same-screen changes. The application must preserve those screens instead. See the implementation contract.</p></div></div>
${rows.join('\n')}
<div class="srow"><div class="ccol"><h2 class="shead">Native scope</h2><p><a class="cite" href="mobile-app/01-today.html">iOS Today</a></p><p class="lede">Only Today is drawn. The native stage remains incomplete; web motion coverage does not imply a finished native app.</p></div></div>
</div></div></div></div>
<p class="caption">The record never moves and the header never arrives. Dates, product-authored lines, waveforms and the composer carry load motion. Notes move only when disclosed. Account and data states remain still except for established control feedback.</p></body></html>\n`);
console.log('Built motion index and design-system specimen. Run design system/build-export.mjs next.');

for (const match of read('motion-index.html').matchAll(/href="([^"]+)"/g)) {
  const target = decodeURIComponent(match[1].split('#')[0]);
  if (target && !fs.existsSync(path.join(root, target))) throw Error(`Missing motion index target: ${target}`);
}
