import { MigrationInterface, QueryRunner } from 'typeorm';

// `users`, and the column on `entries` that points at it. ADR-009's finding was
// that no column in this table could hold the answer to "whose entry is this?",
// so even a server that knew perfectly well who was asking would have nowhere
// to look it up. This migration is that column. Nothing checks it yet.
//
// **`user_id` is nullable, deliberately.** No user can exist until registration
// arrives on Day 9, so `NOT NULL` today would need either a fictional
// placeholder owner or the deletion of every row already in the journal. Both
// are worse than a nullable column. Expand, backfill, contract is the standard
// staged shape and this is the expand step; Day 10 performs the contract once
// real users exist and every entry has one.
//
// ---
//
// **The SQL below was generated by `pnpm migration:generate`, and it rebuilds
// the whole table rather than altering it.** That was read before it was
// trusted, and it is worth seeing rather than assuming, because it is not what
// the file appears to say.
//
// SQLite's `ALTER TABLE` can add a column but cannot add a `FOREIGN KEY`
// constraint to an existing table at all — a constraint is part of the stored
// `CREATE TABLE` text, and the only way to change that text is to write a new
// table, copy the rows across, drop the original and rename. TypeORM knows
// this, and every SQLite migration that touches a constraint looks like the
// dance below.
//
// It does the dance **twice**: once to add `user_id`, then again to add the
// foreign key onto it. One rebuild would have been enough. That is a wasted
// copy of the table and it is left exactly as generated — it is correct, it is
// inside a transaction, and hand-editing generated SQL to save one pass over a
// journal with five rows in it would trade a real risk for nothing.
//
// The dance is only safe because foreign key enforcement is off while it runs.
// TypeORM's `BetterSqlite3QueryRunner.beforeMigration` issues
// `PRAGMA foreign_keys = OFF` and `afterMigration` puts it back to `ON`;
// without that, `DROP TABLE "entries"` in the middle of the second rebuild
// would be checked against constraints pointing at a table that is about to
// come back under the same name.

export class AddUsersAndEntryOwnership1788341821514 implements MigrationInterface {
  name = 'AddUsersAndEntryOwnership1788341821514';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // `users` first, because the foreign key added further down references it
    // and SQLite will not create a constraint pointing at a table that is not
    // there. Three columns and no credential: what a password becomes is Day
    // 9's decision and it has not been made (ADR-009).
    await queryRunner.query(`
            CREATE TABLE "users" (
                "id" text PRIMARY KEY NOT NULL,
                "name" text NOT NULL,
                "created_at" text NOT NULL
            )
        `);
    // Rebuild one: the same table with `user_id` on the end and no constraint.
    // Every existing row is copied by name across three columns, so `user_id`
    // takes its default — NULL — for all of them. That is the whole of the
    // backfill, and it is what makes this migration safe to run against a
    // journal that already has entries in it.
    await queryRunner.query(`
            CREATE TABLE "temporary_entries" (
                "id" text PRIMARY KEY NOT NULL,
                "content" text NOT NULL,
                "created_at" text NOT NULL,
                "user_id" text
            )
        `);
    await queryRunner.query(`
            INSERT INTO "temporary_entries"("id", "content", "created_at")
            SELECT "id",
                "content",
                "created_at"
            FROM "entries"
        `);
    await queryRunner.query(`
            DROP TABLE "entries"
        `);
    await queryRunner.query(`
            ALTER TABLE "temporary_entries"
                RENAME TO "entries"
        `);
    // Rebuild two: identical columns, plus the constraint. The hash in
    // `FK_73b250bca5e5a24e1343da56168` is TypeORM's own deterministic naming —
    // it is derived from the table and column names, so it is stable across
    // machines and is how a later migration would find this constraint again.
    //
    // `ON DELETE NO ACTION` is SQLite's default and is stated explicitly by the
    // generator rather than chosen here. It means deleting a user whose entries
    // still point at them is refused rather than cascading. Nothing can hit
    // that today — there are no users — and Day 9 or Day 10 gets to decide
    // whether deleting an account should delete a journal, which is a product
    // question and not a schema one.
    await queryRunner.query(`
            CREATE TABLE "temporary_entries" (
                "id" text PRIMARY KEY NOT NULL,
                "content" text NOT NULL,
                "created_at" text NOT NULL,
                "user_id" text,
                CONSTRAINT "FK_73b250bca5e5a24e1343da56168" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
            )
        `);
    await queryRunner.query(`
            INSERT INTO "temporary_entries"("id", "content", "created_at", "user_id")
            SELECT "id",
                "content",
                "created_at",
                "user_id"
            FROM "entries"
        `);
    await queryRunner.query(`
            DROP TABLE "entries"
        `);
    await queryRunner.query(`
            ALTER TABLE "temporary_entries"
                RENAME TO "entries"
        `);
  }

  // The same two rebuilds in reverse — drop the constraint, then drop the
  // column, then drop the table — and it is a working `down()` rather than a
  // `throw new Error('not implemented')`, which is what makes this migration
  // something a person can try rather than something they have to commit to.
  //
  // It is genuinely lossy in one direction and that is correct: an entry's
  // `user_id` is discarded on the way back, because the schema it returns to
  // has nowhere to keep it. Reverting after real ownership exists would
  // therefore lose ownership, not merely the constraint. Nothing can hit that
  // today — every `user_id` in the world is NULL — and it is exactly the reason
  // Day 10's contract step will need its own thinking rather than this one's.
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            ALTER TABLE "entries"
                RENAME TO "temporary_entries"
        `);
    await queryRunner.query(`
            CREATE TABLE "entries" (
                "id" text PRIMARY KEY NOT NULL,
                "content" text NOT NULL,
                "created_at" text NOT NULL,
                "user_id" text
            )
        `);
    await queryRunner.query(`
            INSERT INTO "entries"("id", "content", "created_at", "user_id")
            SELECT "id",
                "content",
                "created_at",
                "user_id"
            FROM "temporary_entries"
        `);
    await queryRunner.query(`
            DROP TABLE "temporary_entries"
        `);
    await queryRunner.query(`
            ALTER TABLE "entries"
                RENAME TO "temporary_entries"
        `);
    await queryRunner.query(`
            CREATE TABLE "entries" (
                "id" text PRIMARY KEY NOT NULL,
                "content" text NOT NULL,
                "created_at" text NOT NULL
            )
        `);
    await queryRunner.query(`
            INSERT INTO "entries"("id", "content", "created_at")
            SELECT "id",
                "content",
                "created_at"
            FROM "temporary_entries"
        `);
    await queryRunner.query(`
            DROP TABLE "temporary_entries"
        `);
    await queryRunner.query(`
            DROP TABLE "users"
        `);
  }
}
