import { MigrationInterface, QueryRunner } from 'typeorm';

// The schema as it stood at the end of Day 7, written down for the first time.
// Generated by `pnpm migration:generate` against an empty database, so it is
// TypeORM's own reading of the entity rather than a hand-copy of the old
// `CREATE TABLE IF NOT EXISTS` it replaced (ADR-010).

export class InitialSchema1788262448946 implements MigrationInterface {
  name = 'InitialSchema1788262448946';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE "entries" (
                "id" text PRIMARY KEY NOT NULL,
                "content" text NOT NULL,
                "created_at" text NOT NULL
            )
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            DROP TABLE "entries"
        `);
  }
}
