import { DatabaseSync } from 'node:sqlite';
import { Inject, Injectable } from '@nestjs/common';
import { DATABASE } from '../database/database.module';
import { JournalEntry } from './entry.interface';

// The database's own view of a row. It is not the same type as JournalEntry:
// SQL columns are snake_case, the HTTP contract is camelCase. Neither side is
// wrong, so neither side is bent to match — the translation happens here, in
// the one place that speaks both languages.
interface EntryRow {
  id: string;
  content: string;
  created_at: string;
}

// Nest calls a class like this a "service" (or "provider"). Its job is to
// own data and business logic — as of today that means talking to SQLite in
// hand-written SQL. The controller still won't need to change when the
// storage engine does, because it never touches the data directly; it only
// asks this service for it.
@Injectable()
export class EntriesService {
  // `@Inject` is needed here and not on the controller's `entriesService`
  // because DATABASE is a symbol, not a class. Nest infers dependencies from
  // the parameter's *type*, and `DatabaseSync` as a type says nothing about
  // which instance we want — so we name the token explicitly.
  constructor(@Inject(DATABASE) private readonly db: DatabaseSync) {}

  findAll(): JournalEntry[] {
    // Newest first. Sorting an ISO-8601 string lexicographically is the same
    // as sorting it chronologically, which is a large part of why the format
    // is stored as text rather than a number.
    //
    // Known limit: `createdAt` has millisecond resolution, so two entries
    // written in the same millisecond tie, and SQLite is free to return them
    // in either order. Left alone deliberately — a human cannot write two
    // journal entries in a millisecond, and the fixes (a SQLite-only `rowid`
    // tiebreaker, or a sequence column) either don't survive the move to
    // Postgres or buy determinism nobody has asked for yet.
    const rows = this.db
      .prepare(
        'SELECT id, content, created_at FROM entries ORDER BY created_at DESC',
      )
      // `.all()` is typed `Record<string, SQLOutputValue>[]` — SQLite doesn't
      // know at compile time what columns a query will produce, so the driver
      // can't promise more than "some row objects". The cast is us asserting
      // what the SELECT above already states. It is unchecked by definition:
      // change the column list and the type keeps lying until a test catches
      // it, which is one honest reason people reach for an ORM.
      .all() as unknown as EntryRow[];

    return rows.map(toJournalEntry);
  }

  // Note the parameter: a plain string, not an HTTP body. This service is the
  // data layer, so it stays ignorant of request shapes — which is what lets a
  // job, a CLI, or a test call it without pretending to be a web request.
  create(content: string): JournalEntry {
    const entry: JournalEntry = {
      // Both values are generated by the server, not accepted from the client.
      // That is why the controller has to return the created entry: it is the
      // only way the caller learns what its id and timestamp turned out to be.
      id: crypto.randomUUID(),
      content,
      createdAt: new Date().toISOString(),
    };

    // `?` placeholders with bound values, never string concatenation. The
    // difference is that a prepared statement sends the SQL and the data over
    // separate channels, so a value can never be parsed as SQL — content of
    // `'); DROP TABLE entries; --` is stored as that literal text. There is no
    // untrusted input here yet, but the habit is the defense; the day untrusted
    // input arrives is not the day to start remembering.
    this.db
      .prepare('INSERT INTO entries (id, content, created_at) VALUES (?, ?, ?)')
      .run(entry.id, entry.content, entry.createdAt);

    return entry;
  }
}

function toJournalEntry(row: EntryRow): JournalEntry {
  return {
    id: row.id,
    content: row.content,
    createdAt: row.created_at,
  };
}
