import { Injectable } from '@nestjs/common';
import { EntriesRepository } from './entries.repository';
import { JournalEntry } from './entry.interface';

// Nest calls a class like this a "service" (or "provider"). Its job is
// application logic — the rules about entries that have nothing to do with
// how they are stored. As of today that is thin: it decides what a new entry's
// identity and timestamp are, and delegates every read and write to the
// repository. No SQL appears below, and that is the point: this file no longer
// knows whether entries live in SQLite, in Postgres, or in a file.
@Injectable()
export class EntriesService {
  // No `@Inject` token here, unlike the repository's database parameter.
  // EntriesRepository is a class, so the class itself is the lookup key and
  // Nest can infer the dependency from the type alone.
  constructor(private readonly entriesRepository: EntriesRepository) {}

  findAll(): JournalEntry[] {
    return this.entriesRepository.findAll();
  }

  // Note the parameter: a plain string, not an HTTP body. This service sits
  // below the HTTP layer, so it stays ignorant of request shapes — which is
  // what lets a job, a CLI, or a test call it without pretending to be a web
  // request.
  create(content: string): JournalEntry {
    const entry: JournalEntry = {
      // Both values are generated by the server, not accepted from the client.
      // That is why the controller has to return the created entry: it is the
      // only way the caller learns what its id and timestamp turned out to be.
      //
      // They are generated *here* rather than in the repository or by the
      // schema, which looks arbitrary until you notice that neither call
      // touches the database. A v4 UUID needs no coordination, so the id
      // exists before the row is written; and `createdAt` is product data — the
      // date on the timeline, the value a user might one day want to backdate
      // — not storage bookkeeping. See ADR-004, "Where id and createdAt are
      // generated". The accepted cost is that nothing but this function
      // enforces the format, which is tolerable only while this is the single
      // write path.
      id: crypto.randomUUID(),
      content,
      createdAt: new Date().toISOString(),
    };

    this.entriesRepository.save(entry);

    return entry;
  }

  // `undefined` is passed through rather than converted into an exception. The
  // reason is the same one that keeps SQL out of this file, applied one layer
  // up: a `NotFoundException` is an instruction to write an HTTP response, and
  // this service has to stay callable from a background job or a script where
  // there is no response to write. Turning absence into a status code is the
  // controller's job (ADR-005).
  findById(id: string): JournalEntry | undefined {
    return this.entriesRepository.findById(id);
  }

  findByContent(word: string): JournalEntry[] {
    return this.entriesRepository.findByContent(word);
  }

  countEntries(): number {
    return this.entriesRepository.countEntries();
  }
}
